services:
  postgres:
    image: postgres:16-alpine
    container_name: cache-postgres
    environment:
      POSTGRES_DB: cache_lab
      POSTGRES_USER: cache_user
      POSTGRES_PASSWORD: cache_pass
    ports:
      - "5433:5432"
    cpus: "1.0"
    mem_limit: 512m

  redis:
    image: redis:7-alpine
    container_name: cache-redis
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports:
      - "6380:6379"
    cpus: "1.0"
    mem_limit: 512m

  runner:
    build: .
    working_dir: /app
    environment:
      DB_HOST: postgres
      DB_NAME: cache_lab
      DB_USER: cache_user
      DB_PASSWORD: cache_pass
      REDIS_HOST: redis
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    command: ["sleep", "infinity"]
